---
title: "SIM navigator"
description: "This website contains information about the SIM navigator and how to use it"
output: rmdformats::readthedown
---

# Introduction {#home .unnumbered}

What is the SIM navigator?

The SIM Navigator was

-   An open data set of SIM courses

-   A visual interface to explore SIM courses

-   A zotero library of course readings

# Dataset {#intro .unnumbered}

## Explore {.unnumbered}

The team is currently developing a web application to explore the data. Coming soon.

## Download {.unnumbered}

The data is structured as a relational database comprising 16 tables. Download a .zip file with all the tab-delimited text files [here](data/SimNavigator-202107.zip). You can also download the data as a single Excel file here.

The descriptions of all tables and fields can be found in the [documentation] below.

### Archives {.unnumbered}

There are no archived versions of the dataset at this point.

## Documentation {.unnumbered}

This documentation was Generated by MySQL Workbench Model Documentation v1.0.0 - Copyright (c) 2015 Hieu Le.

#### certificates {.unnumbered}

Courses associated with SIM graduation certificates.

+------------------+-------------+-------------------+------------------------------------------------------------+
| Column           | Data type   | Attributes        | Description                                                |
+==================+=============+===================+============================================================+
| `course_code`    | VARCHAR(45) | PRIMARY, Not null | Course code name                                           |
+------------------+-------------+-------------------+------------------------------------------------------------+
| `certificate_id` | INT         | PRIMARY, Not null | ID number associated with each SIM graduation certificate. |
+------------------+-------------+-------------------+------------------------------------------------------------+
| `required`       | TINYINT     |                   | *comment here*                                             |
+------------------+-------------+-------------------+------------------------------------------------------------+

#### competencies {.unnumbered}

List of program competencies.

+-----------------+-------------+-------------------+-------------------------------------+
| Column          | Data type   | Attributes        | Description                         |
+=================+=============+===================+=====================================+
| `competency_id` | SMALLINT    | PRIMARY, Not null | ID number assigned to a competency. |
+-----------------+-------------+-------------------+-------------------------------------+
| `competency`    | VARCHAR(45) |                   | Name of competency.                 |
+-----------------+-------------+-------------------+-------------------------------------+
| `description`   | LONGTEXT    |                   | Description of competency.          |
+-----------------+-------------+-------------------+-------------------------------------+

#### course_types {.unnumbered}

List of course types.

+-------------------+-------------+-------------------+-----------------------------------------+
| Column            | Data type   | Attributes        | Description                             |
+===================+=============+===================+=========================================+
| `coursetype_id`   | VARCHAR(30) | PRIMARY, Not null | ID number assigned to each course type. |
+-------------------+-------------+-------------------+-----------------------------------------+
| `course_type`     | VARCHAR(45) |                   | Course type (elective, core, etc.)      |
+-------------------+-------------+-------------------+-----------------------------------------+
| `type_definition` | LONGTEXT    |                   | Course type description.                |
+-------------------+-------------+-------------------+-----------------------------------------+

#### courses {.unnumbered}

Courses offered at Dalhousie's School of Information Management.

+------------------+--------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| Column           | Data type    | Attributes        | Description                                                                                                      |
+==================+==============+===================+==================================================================================================================+
| `course_code`    | VARCHAR(45)  | PRIMARY, Not null | Code associated with each course.                                                                                |
+------------------+--------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| `course_title`   | VARCHAR(100) |                   | Name of course.                                                                                                  |
+------------------+--------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| `coursetype`     | VARCHAR(45)  |                   | ID number assigned to each course.<br /><br />**foreign key** to column `coursetype_id` on table `course_types`. |
+------------------+--------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| `offered`        | VARCHAR(45)  |                   | Time of year that a course is offered.                                                                           |
+------------------+--------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| `frequency`      | VARCHAR(50)  |                   | How often a course is offered (every year, alternatiing odd years, etc.)                                         |
+------------------+--------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| `summary`        | LONGTEXT     |                   | Description of course.                                                                                           |
+------------------+--------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| `additionalinfo` | VARCHAR(250) |                   | General notes.                                                                                                   |
+------------------+--------------+-------------------+------------------------------------------------------------------------------------------------------------------+

#### courses_assignments {.unnumbered}

List of assignments in each course.

+--------------------+--------------+-------------------+------------------------------------------------------------------------------------------+
| Column             | Data type    | Attributes        | Description                                                                              |
+====================+==============+===================+==========================================================================================+
| `course_code`      | VARCHAR(45)  | PRIMARY, Not null | Course code name.<br /><br />**foreign key** to column `course_code` on table `courses`. |
+--------------------+--------------+-------------------+------------------------------------------------------------------------------------------+
| `assignment_no`    | VARCHAR(10)  | PRIMARY, Not null | Number of assignemnt.                                                                    |
+--------------------+--------------+-------------------+------------------------------------------------------------------------------------------+
| `assignment_title` | VARCHAR(145) |                   | Name of assignment.                                                                      |
+--------------------+--------------+-------------------+------------------------------------------------------------------------------------------+
| `description`      | LONGTEXT     |                   | Assignment description.                                                                  |
+--------------------+--------------+-------------------+------------------------------------------------------------------------------------------+
| `group`            | VARCHAR(5)   |                   | Assignment is either group work or individual. 0 = individual, 1 = group                 |
+--------------------+--------------+-------------------+------------------------------------------------------------------------------------------+
| `weight`           | VARCHAR(45)  |                   | How much the assignment is worth towards your course grade.                              |
+--------------------+--------------+-------------------+------------------------------------------------------------------------------------------+

#### courses_certificates {.unnumbered}

List of certificates and the courses one can take to obtain them.

+----------------------------+--------------+-------------------+--------------------------------------------------------------------------------------------------------------------------+
| Column                     | Data type    | Attributes        | Description                                                                                                              |
+============================+==============+===================+==========================================================================================================================+
| `certificate_name`         | VARCHAR(150) | PRIMARY, Not null | Name of certificate.                                                                                                     |
+----------------------------+--------------+-------------------+--------------------------------------------------------------------------------------------------------------------------+
| `course_code`              | VARCHAR(45)  | PRIMARY, Not null | Code name of course associated with a certificate<br /><br />**foreign key** to column `course_code` on table `courses`. |
+----------------------------+--------------+-------------------+--------------------------------------------------------------------------------------------------------------------------+
| `certificate_requirements` | LONGTEXT     |                   | Description of what is required to receive a specific certificate.                                                       |
+----------------------------+--------------+-------------------+--------------------------------------------------------------------------------------------------------------------------+
| `additional info`          | LONGTEXT     |                   | Notes about certificates and certain courses.                                                                            |
+----------------------------+--------------+-------------------+--------------------------------------------------------------------------------------------------------------------------+

#### courses_competencies_assignments {.unnumbered}

+-----------------+--------------+-------------------+--------------------------------------------------------------------+
| Column          | Data type    | Attributes        | Description                                                        |
+=================+==============+===================+====================================================================+
| `course_code`   | VARCHAR(45)  | PRIMARY, Not null | **foreign key** to column `course_code` on table `courses`.        |
+-----------------+--------------+-------------------+--------------------------------------------------------------------+
| `competency_id` | SMALLINT     | PRIMARY, Not null | **foreign key** to column `competency_id` on table `competencies`. |
+-----------------+--------------+-------------------+--------------------------------------------------------------------+
| `assignment`    | VARCHAR(250) | PRIMARY, Not null |                                                                    |
+-----------------+--------------+-------------------+--------------------------------------------------------------------+

#### courses_crosslist {.unnumbered}

List of courses with an alternate code name.

+---------------------+-------------+-------------------+----------------------------------------------------------------------------------------------+
| Column              | Data type   | Attributes        | Description                                                                                  |
+=====================+=============+===================+==============================================================================================+
| `course_code`       | VARCHAR(45) | PRIMARY, Not null | Code name for course.<br /><br />**foreign key** to column `course_code` on table `courses`. |
+---------------------+-------------+-------------------+----------------------------------------------------------------------------------------------+
| `other_course_code` | VARCHAR(15) | PRIMARY, Not null | Alternate code name for a course.                                                            |
+---------------------+-------------+-------------------+----------------------------------------------------------------------------------------------+

#### courses_instructor {.unnumbered}

List of instructors and the courses they teach.

+-----------------+-------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| Column          | Data type   | Attributes        | Description                                                                                                      |
+=================+=============+===================+==================================================================================================================+
| `instructor_id` | VARCHAR(10) | PRIMARY, Not null | ID number assigned to an instructor.<br /><br />**foreign key** to column `instructor_id` on table `instructor`. |
+-----------------+-------------+-------------------+------------------------------------------------------------------------------------------------------------------+
| `course_code`   | VARCHAR(45) | PRIMARY, Not null | Course code name.<br /><br />**foreign key** to column `course_code` on table `courses`.                         |
+-----------------+-------------+-------------------+------------------------------------------------------------------------------------------------------------------+

#### courses_learning_objectives {.unnumbered}

List of learning objectives associated with each course.

+-----------------------+--------------+-------------------+---------------------------------------------------------------------------------------------+
| Column                | Data type    | Attributes        | Description                                                                                 |
+=======================+==============+===================+=============================================================================================+
| `course_code`         | VARCHAR(45)  | PRIMARY, Not null | Code name of course.<br /><br />**foreign key** to column `course_code` on table `courses`. |
+-----------------------+--------------+-------------------+---------------------------------------------------------------------------------------------+
| `learning_objectives` | VARCHAR(250) | PRIMARY, Not null | Learning objective associated with a course.                                                |
+-----------------------+--------------+-------------------+---------------------------------------------------------------------------------------------+

#### courses_prerequisites {.unnumbered}

List of courses and their pre-requisites courses.

+----------------+--------------+-------------------+------------------------------------------------------------------------------------------------+
| Column         | Data type    | Attributes        | Description                                                                                    |
+================+==============+===================+================================================================================================+
| `course_code`  | VARCHAR(45)  | PRIMARY, Not null | Code name for a course.<br /><br />**foreign key** to column `course_code` on table `courses`. |
+----------------+--------------+-------------------+------------------------------------------------------------------------------------------------+
| `prerequisite` | VARCHAR(200) | PRIMARY, Not null | Previously taken course(s) required to take a specific class.                                  |
+----------------+--------------+-------------------+------------------------------------------------------------------------------------------------+

#### courses_programs {.unnumbered}

List of courses and the SIM program they are associated with.

+---------------+-------------+-------------------+----------------------------------------------------------------------------------------------------------------------+
| Column        | Data type   | Attributes        | Description                                                                                                          |
+===============+=============+===================+======================================================================================================================+
| `course_code` | VARCHAR(45) | PRIMARY, Not null | Code name of a course.<br /><br />**foreign key** to column `course_code` on table `courses`.                        |
+---------------+-------------+-------------------+----------------------------------------------------------------------------------------------------------------------+
| `program_id`  | VARCHAR(45) | PRIMARY, Not null | Program a course is associated with (ex. MI).<br /><br />**foreign key** to column `program_id` on table `programs`. |
+---------------+-------------+-------------------+----------------------------------------------------------------------------------------------------------------------+

#### courses_technologies {.unnumbered}

List of tecnologies each course uses.

+-----------------+-------------+-------------------+------------------------------------------------------------------------------------------------------------+
| Column          | Data type   | Attributes        | Description                                                                                                |
+=================+=============+===================+============================================================================================================+
| `course_code`   | VARCHAR(45) | PRIMARY, Not null | Code name of course.<br /><br />**foreign key** to column `course_code` on table `courses`.                |
+-----------------+-------------+-------------------+------------------------------------------------------------------------------------------------------------+
| `technology_id` | SMALLINT    | PRIMARY, Not null | Technology used in a course.<br /><br />**foreign key** to column `technology_id` on table `technologies`. |
+-----------------+-------------+-------------------+------------------------------------------------------------------------------------------------------------+

#### instructors {.unnumbered}

List of SIM instructors.

+-----------------+-------------+-------------------+------------------------------------------------------+
| Column          | Data type   | Attributes        | Description                                          |
+=================+=============+===================+======================================================+
| `instructor_id` | VARCHAR(10) | PRIMARY, Not null | ID number assigned to an instructor.                 |
+-----------------+-------------+-------------------+------------------------------------------------------+
| `first_name`    | VARCHAR(45) |                   | Instructor's first name.                             |
+-----------------+-------------+-------------------+------------------------------------------------------+
| `last_name`     | VARCHAR(45) |                   | Instructor's last name.                              |
+-----------------+-------------+-------------------+------------------------------------------------------+
| `status`        | LONGTEXT    |                   | Instructor status (ex. Lecturer, Adjunct Professor). |
+-----------------+-------------+-------------------+------------------------------------------------------+
| `email`         | VARCHAR(45) |                   | Email address of instructor.                         |
+-----------------+-------------+-------------------+------------------------------------------------------+

#### programs {.unnumbered}

List of programs offered by Dalhousie's School of Information Management.

| Column       | Data type   | Attributes        | Description                      |
|--------------|-------------|-------------------|----------------------------------|
| `program_id` | VARCHAR(45) | PRIMARY, Not null | ID number assigned to a program. |
| `name`       | VARCHAR(45) |                   | Name of program.                 |

#### technologies {.unnumbered}

List of possible technologies used in SIM courses.

+-----------------+--------------+------------------------------------+-------------------------------------+
| Column          | Data type    | Attributes                         | Description                         |
+=================+==============+====================================+=====================================+
| `technology_id` | SMALLINT     | PRIMARY, Auto increments, Not null | ID number assigned to a technology. |
+-----------------+--------------+------------------------------------+-------------------------------------+
| `technology`    | VARCHAR(255) |                                    | Name of technology.                 |
+-----------------+--------------+------------------------------------+-------------------------------------+

# Zotero Library {.unnumbered}

A public Zotero Library containing all the School of Information Management course readings can be found [here](https://www.zotero.org/groups/4286370/sim_navigator/library){.uri}.

You can also download the entire Zotero library in BibTeX format [with the associated files](test) or [without the files](test2) (only the references).

# Contributors {.unnumbered}

Thank you to SIM students who helped create the SIM navigator:

-   Theresa Boulos
-   Ratna Dhaliwal
-   Vinson Li
-   Molly McDougall
-   Poppy Riddle

The SIM navigator is a work in progress. If you would like to contribute to its development, please contact [Philippe Mongeon](mailto:pmongeon@dal.ca).
